### ISSUE TITLE
<Enter> sometimes doesn't switch to the selected window in window mode

### ISSUE THREAD

**Issue by Coacher** [DaveDavenport/rofi#454] opened 2016-08-29 12:35 UTC
## Version

Output of `rofi -v`
Version: 1.2.0-17-g20e55e1-dirty (git-r3/HEAD)
## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))
https://bpaste.net/show/948d2bc53fbe
## Launch Command

The commandline used to launch **rofi**
rofi -modi window,run -show window
## Steps to reproduce
- Step 1
  Choose the desired window via arrow keys or by selecting it with a mouse pointer.
- Step 2
  Hit `<Enter>`.
## What behaviour you see
- \- rofi window is closed, but there's no switch to the selected window.
## What behaviour you expect to see
- \- rofi window is closed and there's a switch to the selected window.

I cannot reproduce this problem 100% of the time and sometimes rofi works as expected.
I haven't noticed that this is specific to certain windows, it happens with different programs I use regularly. I'd like to help to solve this issue as it really bothers me. I haven't found any info in the rofi manpage about how to produce log output or other debug info. Please tell what else do you need.

**Comment by DaveDavenport** [comment] 2016-08-29 12:41
I think the problem is related to 'follow mouse' option of many window manager, if the switch happens before rofi releases the mouse, the mouse under the window is focussed again.

It was on my todo  to make a work-around for this soon.

**Comment by Coacher** [comment] 2016-08-29 14:30
My WM (Openbox 3.6.1) supports 'follow mouse' focus mode, but I have it disabled at all times.

**Comment by DaveDavenport** [comment] 2016-08-29 14:31
Curious then. Still I think first closing the rofi window and then switching focus might help (openbox has some focus stealing magic)

**Comment by sardemff7** [comment] 2016-08-29 16:25
May you try `sleep 2 && rofi -show window -kb-accept-entry '!Return'`? (The `sleep` is there to avoid triggerring the binding directly.)
It probably won’t change anything but with enough luck… (Or lack of luck, considering what weird bug it would reveal if it worked.)

**Comment by Coacher** [comment] 2016-08-29 16:53
@sardemff7, I've replaced my initial command with yours. I cannot reproduce this problem right away, but I need a couple more days to test due to the random nature of this problem.

**Comment by DaveDavenport** [comment] 2016-08-30 06:17
Added a test that umaps  the rofi window before requesting the switch. For me on I3, with follow mouse, this works.

**Comment by Coacher** [comment] 2016-08-30 07:14
It's still reproducible with the @sardemff7's command.
I'll try with your changes now, @DaveDavenport.

**Comment by DaveDavenport** [comment] 2016-08-30 07:20
Thanks.

**Comment by Coacher** [comment] 2016-08-30 08:19
Still reproducible with `Version: 1.2.0-26-gef50986-dirty (git-r3/HEAD)` with both my original command and the command suggested above.

**Comment by DaveDavenport** [comment] 2016-08-30 08:24
to bad. :frowning:

**Comment by DaveDavenport** [comment] 2016-08-30 15:35
I installed openbox on my laptop, can you explain what are the steps that have the highest probability to reproduce the problem.

**Comment by Coacher** [comment] 2016-08-31 05:10
@DaveDavenport, here's my openbox config: https://gist.github.com/Coacher/b771dd9a33cded8fd79965c4fa9fa55d

Here WS stands for workspace.

I usually have 1 or 2 Firefox windows opened on WS 1, Konversation IRC client on WS 2, smplayer or mpv on WS 3, and a variety of Konsole, gVim, Okular, Kile windows open on WS 4-6.

While trying to reproduce this problem I've noticed that it happens somewhat more often if I switch furiously between windows on WS 1-3. Switching away from an open Firefox or Konversation window fails somewhat more often than from other windows.

There's slightly different problem that is easier to trigger. Maybe you will be able to reproduce it, but I am unsure if this a rofi problem and not some firefox focus stealing magic. Have 2 Firefox windows open on WS 1, say we call them F1 and F2. Focus F2, switch to some other WS. Now switch to F1 via rofi. You should see that WS is changed to 1, F1 window is raised, but focus is still in F2.

Thank you very much for your help!

**Comment by DaveDavenport** [comment] 2016-09-02 07:40
Can you test latest patch?

**Comment by DaveDavenport** [comment] 2016-09-02 07:43
Issue related to #138

**Comment by Coacher** [comment] 2016-09-02 18:07
> Can you test latest commit?

The problem is still reproducible.

**Comment by DaveDavenport** [comment] 2016-09-02 18:11
Not sure how to fix this then? I unmap the window, ungrab the keyboard and then switch.

(Just added release pointer, saw I forgot that one).

**Comment by Coacher** [comment] 2016-09-02 18:17
Could it be libxcb problem? I have 1.11.1 installed.
Could it be `CacheState`-related? How can I test this?

**Comment by DaveDavenport** [comment] 2016-09-02 18:18
You are just guessing?

I suspect it might be the focus stealing prevention in openbox, possible to turn this off?

**Comment by Coacher** [comment] 2016-09-02 18:20
> You are just guessing?

Yes and no. rofi does libxcb calls so maybe it's libxcb bug.

**Comment by Coacher** [comment] 2016-09-02 18:21
> I suspect it might be the focus stealing prevention in openbox, possible to turn this off?

I don't know a config option for this. I'll try patching it out.

**Comment by DaveDavenport** [comment] 2016-09-02 18:22
I suspect this, because switching between workspaces is a command I send openbox, if this is not happening it is because it is not 'obeying' it.

**Comment by Eizen** [comment] 2016-11-07 07:30
Same happening here. Cannot reproduce all the time. Will try with latest version of git soon.

Version: 1.2.0
Command used: `rofi -show window`
wm: i3-gaps
Apps opened at the time: Firefox (only one instance), urxvt, spotify, atom

**Comment by DaveDavenport** [comment] 2016-11-07 07:57
Weird, I *never* had this issue under i3-gaps. 
Rofi does:
`xcb_ewmh_request_change_current_desktop` if we are not already on this desktop.
`xcb_ewmh_request_change_active_window`

@airblader Any ideas about this one?

(I do have issues with spotify stealing focus anytime the mouse pointer is over it screen, even if you move focus away, it will grab it again).

**Comment by Airblader** [comment] 2016-11-07 20:28
@DaveDavenport Does that commit fix it? I wouldn't know the cause immediately and would've suggested looking at i3 log files.

**Comment by DaveDavenport** [comment] 2016-11-07 21:31
I don't know, I cannot reproduce it.. @Eizen  can you test?

**Comment by Eizen** [comment] 2016-11-08 22:06
Thanks @DaveDavenport . That last commit seems to have fixed it for me. Have been testing all day without issues now. Will let you know if anything changes.

**Comment by DaveDavenport** [comment] 2016-11-09 07:52
Good to hear.

Thanks for testing.

Will close this for now.

**Closed by DaveDavenport** 2016-11-09 07:52 UTC
Labels: bug, Needs Testing

**Comment by mantono** [comment] 2017-07-03 15:03
I have this issue with rofi 1.3.1, but in i3-wm. Should I create a new issue or use this one?
I have `focus_follows_mouse no` in my i3 config.

**Comment by DaveDavenport** [comment] 2017-07-04 07:16
Please file a new bug report.
