### ISSUE TITLE
Rofi 1.4.2 doesn't capture ←, ↑, →, ↓ binding to keys to work in combination with Mode_switch (it works in 1.3.1)

### ISSUE THREAD

**Issue by marcellmars** [DaveDavenport/rofi#744] opened 2017-12-25 20:25 UTC
## Rofi version

1.4.2.

## Configuration

https://gist.github.com/marcellmars/348c1af5b7d9c3fa76ae4e4e172c1995

## Launch Command

`rofi -modi run,drun -show run -font "Terminus (TTF) 24"
`

but it doesn't really matter...

## Steps to reproduce

* run rofi 1.4.2 with keyboard layout where Mode_switch brings  ←, ↑, →, ↓, enter, backspace and delete to some of the keys

## What behaviour you see

* it doesn't capture  ←, ↑, →, ↓, enter, backspace and delete

## What behaviour you expect to see

* it should work as it works with 1.3.1-2 (debian) and any other app i run on my system

## Probably better explanation

i have ←, ↑, →, ↓, enter, backspace and delete binded to Mode_switch in combination with several other keys. it stopped working in rofi with the latest upgrade (1.4.2). my guess this could be the commit which is related to that: https://github.com/DaveDavenport/rofi/commit/7f7da66c1a92a8f034fcb4c4533ce57bed45ce64

in my keyboard layout file in /usr/share/X11/xkb/symbols/my_keyboard i have things like:

`key <LCTL> {[ Mode_switch, Multi_Key]};
`

which would then let me do:

```
    key <AC06> { [ h, H], [Left,  any]};
    key <AC07> {[ u, U], [Down, any]};
    key <AC08> {[i, I], [Up, any]};
    key <AC09> {[o, O], [Right, any]};
    key <SPCE> {[space, space], [Return, any]};
    key <CAPS> {[Escape]};
    key <LWIN> {[Control_L]};
```

that config could be run by:

`setxkbmap my_keyboard -option
`

rofi runs as this:

`rofi -modi run,drun -show run -font "Terminus (TTF) 24"
`

the theme is configured (depending on the rofi version) in ~/.config/rofi/config as:

```
rofi.theme: /usr/share//rofi/themes//solarized_alternate.rasi
#include "/usr/share//rofi/themes//solarized_alternate.theme"
```

it worked fine before i upgraded to 1.4.2 and it works fine now after downgraded to 1.3.1
i didn't notice any particular application would have problems with my_keyboard.

my guess is that any keyboard which would have **Mode_switch** assigned to some key and then another one having **Down** set together with **Mode_switch** to do the **↓** should be minimal enough setup to test. these are the related lines from my keyboard configuration:

```
    key <LCTL> {[ Mode_switch, Multi_Key]};
    key <AC07> {[ u, U], [Down, any]};
```

**Comment by sardemff7** [comment] 2017-12-25 20:47
AFAICT, duplicate of #611, with a fix pending (because the fix is after a new feature in a submodule, so we cannot bring it without potentially break the mouse stuff).

**Closed by sardemff7** 2017-12-25 20:47 UTC

**Comment by sardemff7** [comment] 2017-12-25 20:50
(See `wip/mouse-rework` for a fix.)

**Comment by marcellmars** [comment] 2017-12-26 02:21
compiling it from wip/mouse-rework branch works!
