### ISSUE TITLE
Using rofi in Gtk applications

### ISSUE THREAD

**Issue by mardukbp** [DaveDavenport/rofi#413] opened 2016-05-31 07:57 UTC
rofi is so awesome that I want to have it inside all the apps I use. In particular, currently I want to implement rofi inside [astroid](https://github.com/gauteh/astroid) for filtering the query history and navigating the filesystem when adding attachments.

But instead of spending time reading, understanding and implementing rofi again I thought that it would be better if rofi could be integrated into any Gtk app (running on Linux). I am thinking that this would involve separating the rofi core into a shared library, but if there is a better way I would like to know.

**Comment by sardemff7** [comment] 2016-05-31 09:13
Duplicate of #212.

**Closed by sardemff7** 2016-05-31 09:13 UTC

**Comment by mardukbp** [comment] 2016-05-31 12:47
I was not aware of #212. However, I did not mean talking to rofi from a program, but instead using an abstraction layer that enables rofi list filtering to be implemented with any GUI toolkit. I am thinking of rofi as a GUI widget. I would appreciate comments and suggestions on how to realize this.

**Comment by sardemff7** [comment] 2016-05-31 13:52
You want to decouple the filtering part only? Like `char **rofi_magic_get_me_matching_stuff(char **list, char *entry)`?

That could be done, but it won’t be easy.
The easiest way is probably to implement a library, and then port rofi to use it.

Anyway, this is a non-goal for rofi itself.

**Comment by mardukbp** [comment] 2016-06-01 18:40
> You want to decouple the filtering part only?

Yes, exactly.
 
> That could be done, but it won’t be easy.

I am going to try.
