### ISSUE TITLE
DRUN Browser matches multiple visible and invisible fields, causing unexpected results.

### ISSUE THREAD

**Issue by BonarBeavis** [DaveDavenport/rofi#656] opened 2017-08-19 09:49 UTC
## Version

1.3.1

## Configuration

[follow instructions](https://gist.github.com/DaveDavenport/68c148d41c91186f1055f498272767a2)

## Launch Command

drun

## Steps to reproduce

* input 'fi'

## What behaviour you see

* 'Paperwork' is the first match

## What behaviour you expect to see

* 'Paperwork' should not be the first match for the search 'fi'

**Comment by DaveDavenport** [comment] 2017-08-19 09:53
DRun mode searches through many fields in the Desktop file. That might be providing a very accurate match.

**Comment by BonarBeavis** [comment] 2017-08-19 09:59
This explains a lot. Can I turn this off?

**Comment by DaveDavenport** [comment] 2017-08-19 10:04
No, this is not configurable.

**Comment by BonarBeavis** [comment] 2017-08-19 10:14
So this is intended behavior, even if it goes against the principle of least astonishment?

**Comment by DaveDavenport** [comment] 2017-08-19 12:20
That is very subjective.

If I type in 'Text editor' I expect to see all text editors, if I type in 'office' I expect to see my office tools.

The problem is there is not one solution that pleases everybody, if I try to please everybody and make 100034 options, the tool becomes unmaintainable.  (got into this mess before with GMPC that was massif and I only used 1% myself).

**Comment by BonarBeavis** [comment] 2017-08-19 16:20
I get your point, keep it simple. But then not searching all fields in the desktop entry should be implemented. I would assume, that the more general use case for drun is to launch applications and not to search for applications. 
Furthermore by including all fields the results are random for small search strings.
For example: Searching `fi` gives Steam as the first result, but searching `st` gives htop as the first result.

Maybe a solution could be: Only search the strings which are actually displayed by rofi.
Then the search for `text` still would give all text editors, but not all applications, which have `text` somewhere in their description.

**Comment by DaveDavenport** [comment] 2017-08-19 19:57
I don't agree.   rofi should **find** you what you want, so text editor -> should give all text editors.
Then the history part of rofi remembers your favorite commands and makes sure they are sorted at the top. So next time just type a few characters and your command is on top and you can quickly **run** it.


( It sounds like the functionality of the 'run' switcher matches more what you want, that just matches the executable name.)

**Comment by BonarBeavis** [comment] 2017-08-19 23:42
I was about drun and that it matches the token against the category: [here](https://github.com/DaveDavenport/rofi/blob/c5607bfbd0f4b393eba1db24aa85abb75581fbba/source/dialogs/drun.c#L692) is the "offending part". The arbitrary categories wreak havoc with the matches. And because drun does not show the categories, the user is left to wonder wh,y a search for "only" returns htop.

**Comment by DaveDavenport** [comment] 2017-08-20 08:36
I added category matching on multiple requests (.f.e. #499).  Ill leave this one here, if  it gets enough votes I will reconsider.

**Comment by alexozer** [comment] 2017-10-12 02:03
I also would really like to see a way for executable / title name matching prioritized over description. I'd argue that "finding all desktop files that match a certain category / description like text editor" happens a lot less frequently than trying to open one specific program with a certain name quickly.

I run into a situation like this very often:
![rofi](https://user-images.githubusercontent.com/2074322/31475651-05fc9316-aed0-11e7-9ae8-1307067e0aab.png)

**Comment by DaveDavenport** [comment] 2017-10-13 08:50
@alexozer  Please follow the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md) and make a new issue. Do not make meta issues, as they become hard to keep track off.

**Comment by alexozer** [comment] 2017-10-15 04:25
@DaveDavenport really sorry, I posted on the completely wrong issue by accident.

**Comment by DaveDavenport** [comment] 2017-10-21 09:19
Fixed with merge request #690.

**Closed by DaveDavenport** 2017-10-21 09:19 UTC
