### ISSUE TITLE
Rofi freezes sometimes on exit

### ISSUE THREAD

**Issue by Eisfreak7** [DaveDavenport/rofi#576] opened 2017-03-18 21:06 UTC
## Version

1.3.1

## Configuration

[Output of `rofi -help`](http://sprunge.us/jdZP)

## Launch Command

`rofi -show`

## Steps to reproduce

This is where it gets tricky. What I know for sure:  
Sometimes, when exiting the rofi window by pressing `escape` while holding `super`, rofi freeezes.
By freezing I mean:

- The process exits (the terminal shows the prompt again)
- The rofi window stays for ~30 seconds. While the window is still there, keyboard input is blocked (rofi doesn't react but apparently still grabs it).

I'm pretty sure another factor is that I've bound capslock to be escape when pressed, ctrl when held (with xcape). I couldn't reproduce it with the regular escape key, but since I can't reliably reproduce it I am not sure that the binding is relevant.

As an aside: While testing (repeatedly executing `rofi -show` and hammering on `super` & `escape`) I encountered another bug:  
Rofi exited, but after that the keyboard was completely unresponsive (even after replugging) until reboot.
That only happened twice while testing and never "naturally".

**Comment by DaveDavenport** [comment] 2017-03-18 21:36
This sounds weird, rofi (except for filtering) is single threaded (just one main loop).
So if rofi exists normally it should already have released keyboard, unmapped and destroyed the window.

Q: Can you check if rofi exited normally and did not segfault.

Rofi should also not accept the escape key as cancel if super is held. Neither control-escape.

Q: Can you paste your exact setup with xcape. I don't know this program.
I would not be surprised if this is causing all the weirdness.

The keyboard unresponsive.. Try the Sys-req key to get keyboard back again and switch  to a virtual terminal (ctrl-alt-f2) and see if rofi is still running.

**Comment by Eisfreak7** [comment] 2017-03-18 21:53
I enabled coredumps with `ulimit -c unlimited` (zsh) before triggering the bug and no file named `core` appeared, so I don't think it is a segfault (or how should I determine it?).

Yes I think the bug is triggered when I release escape and super at about the same time, so not quite pressing escape while super is held. Its hard to say exactly.

[xcape](https://github.com/alols/xcape) is a daemon that can intercept certain keys and allows double binding them (pressed -> escape. held in combination with other key -> ctrl). The relevant part of the configuration:
```
# Bind capslock to left control
xmodmap -e 'remove Lock = Caps_Lock'
xmodmap -e 'remove Control = Control_L'
xmodmap -e 'keysym Control_L = 0'
xmodmap -e 'keysym Caps_Lock = Control_L'
xmodmap -e 'add Control = Control_L'
# Send escape when left control is pressed alone
xcape -e 'Control_L=Escape'
```

I don't think I have a `Sys-req` key. What should that key do? Switching to a virtual terminal didn't work either. As I said, the second bug was extremely rare (and that one appeared when testing with "normal" escape, no `xcape` involved).

**Comment by DaveDavenport** [comment] 2017-03-18 21:58
1. Check the return status of the program.

2. will try to reproduce.

3. You probably have, but they are not always clearly labeled.  (sometimes it is alt-print screen)  sys-req + r will release the keyboard from raw mode (X11) and allows you to switch to virtual terminal. See link.

**Comment by Eisfreak7** [comment] 2017-03-18 22:10
1. Return status `0`.
2. If I encounter the second bug again, I'll just try to ssh in from another device. I just tried that with the first bug (while the terminal is back to the prompt but the window is still shown) and confirmed that no process called `rofi` is running.

**Comment by DaveDavenport** [comment] 2017-03-18 22:12
It is really strange that the window would still be visible if rofi is not running.

Can you list all X11 windows next time when you get into this state? see if rofi is still visible?
```
DISPLAY=:0 xwininfo  -root -tree
```

**Comment by Eisfreak7** [comment] 2017-03-18 22:19
Interestingly, that command kills the window.
The moment I execute it, the rofi window disappears. The window isn't listed in the output.

In case you missed it, I edited my last post. I do think that it happens more often with super pressed though.

**Comment by DaveDavenport** [comment] 2017-03-18 22:22
That is extremely weird, like something is hanging X11. (and xwininfo is somehow unlocking it again).

**Comment by Eisfreak7** [comment] 2017-03-18 22:31
Yes. That would also explain why the problem magically solves itself after a few seconds, something probably will trigger something similar to xwininfo regularly.

But rofi is the only program I had this issue with. Maybe something isn't properly deregistered or something on exit (I have no idea how X works)?
Or maybe the issue is elsewhere but somehow only manifests itself through rofi since it blocks the keyboard, which stays in that state because of it? But the visual part (the rofi window not disappearing) should happen with more programs then, shouldn't it?

**Comment by DaveDavenport** [comment] 2017-03-18 22:38
**rofi** is kinda special, it tells the window manager to ignore it, and then grabs all the keyboard and mouse input.
Most applications do not do this.

Things to try out?
* What you can do is tell rofi to only act on key-release: 
```bash
rofi -show run -kb-cancel '!Escape'
```
* Run rofi in normal window mode where it does not grab keyboard and acts as a normal window.
```bash
rofi -show run -normal-window
```

**Comment by Eisfreak7** [comment] 2017-03-18 22:44
I think it doesn't happen with `rofi -show run -kb-cancel '!Escape'`. I tried it about 20 times and normally I'm able to trigger the issue with 5-10 tries.

It *does* happen with `-normal-window` though. Then the rofi window stays where it is, but keyboard isn't blocked and focusing another window kills the rofi window.

**Comment by DaveDavenport** [comment] 2017-03-18 23:01
Curious.  thanks for testing.
Seems the combination xcape and rofi is an unhappy one.
Hopefully the cancel on key release workaround is good enough.

**Comment by Eisfreak7** [comment] 2017-03-18 23:09
Thank you for helping me so quickly.
Its good enough for me.
While tresting the `-kb-cancel` workaround I triggered the second issue again (no xcape).
The system is still running, keyboard blocked, rofi process not running. Anything you want me to test?

**Comment by DaveDavenport** [comment] 2017-03-18 23:12
check if rofi is still running?  does calling xwininfo unblock it again?

**Comment by Eisfreak7** [comment] 2017-03-18 23:13
No, rofi is not running and xwininfo doesn't unblock it.

**Comment by DaveDavenport** [comment] 2017-03-18 23:16
I cannot explain this one (not an X11 expert (its a big box of black voodoo)). 
I cannot say I have ever heard of this happening while rofi is **not** running.
(for completeness sake:
What distro, version and window manager are you running)

**Comment by Eisfreak7** [comment] 2017-03-18 23:21
Maybe the keyboard just somehow isn't freed on exit?
archlinux, fully updated, herbstluftwm 0.7.0
This issue doesn't bother me much since I never had it happen when not actively "provocing" rofi.
So if you don't want to investigate we can close this. If you do I'll gladly help.

**Comment by DaveDavenport** [comment] 2017-03-18 23:25
Even if I don't release the keyboard, the application quitting/killing normally is enough to release it too.
As I said, not sure. I will try again later to see if I can re-produce this.

**Comment by Eisfreak7** [comment] 2017-03-18 23:28
If thats relevant: `DISPLAY=:0 xdotool key a` also does nothing.
Okay.

**Comment by DaveDavenport** [comment] 2017-03-19 16:20
Will re-open if stuff needs to be fixed in rofi.

**Comment by DaveDavenport** [comment] 2017-03-21 18:48
do you have an AMD video card?

**Comment by DaveDavenport** [comment] 2017-03-21 19:07
(can you test if latest commit fixes the last issue)

**Comment by Eisfreak7** [comment] 2017-03-21 21:54
Yes I do.

I tested it with a build from Master. The freeze still occurs. I also triggered the first bug two times (besides the workaround *and* without xcape).

**Comment by rychipman** [comment] 2017-03-23 08:05
Just wanted to note that I am also experiencing this issue. Rofi is a regular part of my daily workflow, so this bug may be a deal breaker for me if we can't figure it out 😞

Let me know if I can do anything to help debug

**Comment by DaveDavenport** [comment] 2017-03-23 08:07
@rychipman can you give rofi version, distribution, graphics card?

**Comment by rychipman** [comment] 2017-03-23 08:10
rofi version: 1.2.0-248-ge7375f7-dirty
distro: arch
graphics card: intel integrated graphics

**Comment by DaveDavenport** [comment] 2017-03-23 08:13
Can you update your rofi?

**Comment by rychipman** [comment] 2017-03-23 08:18
updated to master, but still having the same issue

**Comment by DaveDavenport** [comment] 2017-03-23 08:33
Since when did this problem manifest itself.

**Comment by rychipman** [comment] 2017-03-23 08:36
The first time I noticed was at some point in the last couple months, but I don't think I can pin it down more precisely than that.

As with the reporter, the bug usually manifests itself when I open and close rofi 5-10 times. In case it matters, I use a window manager (not a desktop environment). Have you been able to reproduce?

**Comment by DaveDavenport** [comment] 2017-03-23 08:40
No, not on arch or ubuntu or debian or void.

What window manager?

How do you close it? click outside the window? accept entry? cancel (Escape). 
The more I know the more likely I can reproduce it.

**Comment by rychipman** [comment] 2017-03-23 08:43
So far, I have been able to reproduce by clicking outside the window or pressing escape. As far as window managers, the behavior is identical on bspwm and herbstluftwm.

**Comment by DaveDavenport** [comment] 2017-03-23 09:09
It looks like (but haven't been able to confirm):
That somehow X11 does not process the last messages from rofi (as rofi quits normally and unmaps and destroys the window). Then when you use xwininfo (or something else) to send another message it sees it and processes it.

Adding an extra `xcb_flush` seems not to help.

**Comment by DaveDavenport** [comment] 2017-03-23 17:46
Note: Unable to reproduce under herbstluftwm.

**Comment by Rubonnek** [comment] 2017-03-23 19:25
Just now I was able to reproduce this issue in `i3-wm`. Took a lot more tries to reproduce than in `herbstluftwm`.

Here's what I did to reproduce it in `herbstluftwm` with `rofi` version `1.3.1`:

1. Start two instances of X. In my case `DISPLAY=:0` was in `tty1` running `i3` and `DSPLAY=:1` was in `tty2` running `herbstluftwm`.
2. From  `DISPLAY=:0`, open a terminal and run
```shell
DISPLAY=:1; for i in `seq 1 20`; do rofi -show; done
```
3. Switch to `DISPLAY:=1` where `herbstluftwm` is running and keep clicking as fast as possible regardless of whether `rofi` is on screen or not, to close `rofi` .
4. Repeat steps 2 and 3 when `rofi` stops showing up and until the second bug shows -- `rofi` will show up on screen and stay there even when clicking outside of it.

In my case `DISPLAY=:1`, where `herbstluftwm` is running, freezes for more than 30 seconds. I can't switch the workspace, nor create new windows.

Note: `echo $?` returns `0` in my case too.

**Comment by DaveDavenport** [comment] 2017-03-23 19:58
I already tried that.. for loop of  2000 times in a row, both with clicking and with hitting escape both with and without composite manager.... 

As I said before I do not see why this happens, as rofi takes (as far as I can tell) the correct steps on shutdown (that clearly happens).   unmap, destroy, flush, disconnect. (had this checked  with the extra debug output produced by setting G_MESSAGES_DEBUG=all ).

@Airblader as my source of  xcb wisdom,  do you have any ideas on this one?

**Comment by Airblader** [comment] 2017-03-25 12:47
The only thing I could imagine where rofi would cause this when exiting is if rofi grabbed the server. Does it ever do that?

**Comment by DaveDavenport** [comment] 2017-03-25 12:49
@Airblader  what do you mean with 'grabbed the server'?
It grabs the keyboard/mouse, but it makes sure to release those again. (I do an explicit release on shutdown even I released them before).

**Comment by Airblader** [comment] 2017-03-25 12:54
I mean XGrabServer / xcb_grab_server (not grabbing the keyboard / mouse). If simply querying X for a list of windows makes it disappear immediately it surely seems like X is at fault, not rofi. But I will admit that this sounds really odd.

**Comment by DaveDavenport** [comment] 2017-03-25 12:59
No,  I never do that.  It is an odd problem, that seems to be very machine dependent if it can be reproduced.
@Airblader Thanks for giving it some though.

**Comment by chrissound** [comment] 2017-03-25 13:04
I have this issue as well.

I worked around it by doing 'pkill rofi' at the end of the script. I too have an AMD graphics.

**Comment by DaveDavenport** [comment] 2017-03-25 13:10
@chrissound  that is odd.. Other people indicate that rofi correctly quits. pkill should not do anything. But it gives me something to look at.

(Also curious (and counter productive) that apparently this  problem existed for a long time yet nobody reports it, now that is reported everybody comes out of the wood... )

**Comment by Airblader** [comment] 2017-03-25 13:12
Depending on how reliably it can be reproduced I'd suggest just bisecting the issue.

**Comment by DaveDavenport** [comment] 2017-03-25 13:14
I haven't been able too (regrettable), but people (now) reported it back to version more then 1/2 a year ago.

**Comment by DaveDavenport** [comment] 2017-03-25 13:27
Can anybody update and send me the output of rofi running with the environment variable:
```
G_MESSAGES_DEBUG=all
```
when this problem happens?

(and if somebody has the time, try to find the origin of the issue with git bisect.

**Comment by Eisfreak7** [comment] 2017-03-29 16:57
Running git bisect (and opening & closing rofi >2100 times :D) shows that 93cb9ee7eb81172b6258dfdae998cefc2b78f0cb is the evil one (introducing the first bug).
The output of the command doesn't differ significantly from the output of a successful run, but here it is anyway:
http://sprunge.us/eDcB
and a successful one to compare:
http://sprunge.us/diQd

I couldn't reproduce the second bug again.

**Comment by DaveDavenport** [comment] 2017-03-29 17:04
Great so it broke when we moved from xlib to xcb.

**Comment by sardemff7** [comment] 2017-03-29 17:12
Just in case, can you test the `wip/wayland` branch (passing `./configure --with-display-backend=xcb`) to see if you can reproduce the bug? (It should be still there, but if it’s not, then your bisect probably missed a good commit somewhere in the middle…)

**Comment by Eisfreak7** [comment] 2017-03-29 17:20
Yes, its still there on `wip/wayland`.

**Comment by Eisfreak7** [comment] 2017-03-29 17:22
In theory its possible that I missed a bad commit, since I can't reliably reproduce the bug.
However, I can usually reproduce it within <1 min and I tried it for significantly longer with the last working commit.
In case its relevant, here's the bisect log: http://sprunge.us/BZfP

**Comment by DaveDavenport** [comment] 2017-03-29 17:51
Can  you try the last commit on the master branch, see if that helps? I now force a sync (wait until all pending events are processed) with the X11 server before disconnecting.

**Comment by Eisfreak7** [comment] 2017-03-29 19:10
Looks good, I can't reproduce it with the latest master.

**Comment by Airblader** [comment] 2017-03-29 19:18
That would sound odd to me. I'd expect the events to be implicitly flushed on disconnect.

**Comment by Airblader** [comment] 2017-03-29 19:18
(Not saying that it is the case. More along the lines of this could be mentioned to the Xorg mailing list)

**Comment by Eisfreak7** [comment] 2017-03-29 19:25
I just tested it again to be sure. I'm as certain as I can be that the bug doesn't occur with the last commit on the master branch.

**Comment by DaveDavenport** [comment] 2017-03-29 20:07
@Airblader  yep, documentation indicates it is not needed.
But it was a.) worth the try, b.) i3bar (and companions) do it.

**Comment by sardemff7** [comment] 2017-03-29 20:14
@DaveDavenport Which documentation?
From the [code](https://cgit.freedesktop.org/xcb/libxcb/tree/src/xcb_conn.c?id=b0e6c2de09c7474868dd7185674fa113a5c2e0aa#n371) it does nothing like that. OTOH, the same [code](https://cgit.freedesktop.org/xorg/lib/libX11/tree/src/ClDisplay.c?id=a72d2d06c002b644b7040a0a9936c8525e092ba8#n45) in Xlib calls `XSync`.

**Comment by DaveDavenport** [comment] 2017-03-29 20:19
Cannot remember where, I saw it a couple of times

https://xcb.freedesktop.org/tutorial/basicwindowsanddrawing/
> This functions also flushes all pending requests to the X server, and then waits until the X server finishing processing these requests. In a normal program, this will not be necessary (we'll see why when we get to write a normal X program), but for now, we put it there.

From the 1.0 release:
> XCB no longer provides a sync function. Most callers of this function
should use xcb_flush instead, which usually provides the intended
functionality and does not require a round-trip to the server. If you
really need this functionality, either use xcb_get_input_focus like sync
used to do, or use the xcb_aux_sync function from the xcb-aux library in
xcb-util. However, note that we do not consider the libraries in
xcb-util remotely stable yet.
.

**Closed** 2017-03-30 06:12 UTC
