### ISSUE TITLE
drun duplicates entries from /usr/share/applications/

### ISSUE THREAD

**Issue by michja** [DaveDavenport/rofi#648] opened 2017-08-08 01:12 UTC
## Version
Version: 0.15.11

## Configuration
https://gist.github.com/michja/ebb0a80429277538c5865dae9cbe9a87

## Launch Command
rofi -show drun -modi drun -width 1366 -fg "#a2a2a2" -bg "#232221" -hlfg "#14161F" -hlbg "#0aa899" -bc "#14161F" -location 0 -lines 10 -bw 0 -font "Operator Mono 18" -padding 100 -separator-style none -opacity 90 -line-margin 1 -eh 2 -fullscreen 

## Steps to reproduce
* Have .desktop files in /usr/share/applications
* Run rofi drun

## What behaviour you see
* All .desktop entries from /usr/share/applications/ appear twice

## What behaviour you expect to see
* All .desktop entries from /usr/share/applications/ appear once

## Workaround
This doesn't happen for /usr/local/share/applications/ so I 'fixed' it by moving all files there.
If some files are in /usr/share... and others in /usr/local... only the entries from /usr/share... are duplicated

**Comment by carnager** [comment] 2017-08-08 04:47
You are using an unsupported old version, please update and try again.

**Comment by DaveDavenport** [comment] 2017-08-08 06:44
duplicate of #453

**Closed by DaveDavenport** 2017-08-08 06:44 UTC

**Comment by michja** [comment] 2017-08-08 16:20
I've got 1.3.1 now and its working great. I had the latest version from ubuntu apt-get, never considered that I'd be so far behind. So that was dumb not checking that. I did search before posting though and this was a different issue to the one that it's been marked a dupe of. Not that it matters now.
Thanks for the help.

**Comment by DaveDavenport** [comment] 2017-08-08 16:40
I just linked it up the last "duplicate drun entry topic" to create the links. The actual problem has been fixed for a long time.
Happy it works well in 1.3.1.
