### ISSUE TITLE
[Feature Request and/or Question] How do I turn off italics / How do I turn off generic names?

### ISSUE THREAD

**Issue by anonaii** [DaveDavenport/rofi#858] opened 2018-09-26 21:40 UTC
## Version
Output of `rofi -v`
Version: 1.5.0

## Configuration
https://gist.github.com/anonaii/67eb0055e99fe1851e259885931d8bd0
https://gist.github.com/anonaii/14014106a56eda6ac1e77cc49628e4ee

## Launch Command
`rofi -show drun`

## Steps to reproduce

* Set your font as a bitmap without italics (I use terminus)
* Run the `drun` modi

## What behaviour you see

Generic names are shown in italics, even though the font lacks italics. This created weird sideways text.

## What behaviour you expect to see

Non-italicized text for generic names, or no generic names at all.

![2018-09-26-163751_1366x768_scrot](https://user-images.githubusercontent.com/43378896/46110916-ce078300-c1aa-11e8-9e45-cba4722f0049.png)

**Comment by DaveDavenport** [comment] 2018-10-05 14:59
duplicate of #812 ?

**Comment by DaveDavenport** [comment] 2018-10-17 21:05
added feature 'drun-display-format' should allow you to fix this.

**Closed by DaveDavenport** 2018-10-17 21:05 UTC
