### ISSUE TITLE
PATH and alias don't work in the I3 and bspwm config

### ISSUE THREAD

**Issue by Brainzman** [DaveDavenport/rofi#408] opened 2016-05-21 13:29 UTC
Hi guys i have a problem . When enter that in my zsh shell 
`rofi -show run`

I have rofi whith all my alias and the program of my PATH

but when i add this in my i3 config (and its the same result in bspwm config) : 
`zsh -c "rofi -show run"`

I don't have my alias and my PATH

**Comment by DaveDavenport** [comment] 2016-05-21 14:18
Duplicate of #405?

**Closed by DaveDavenport** 2016-05-21 14:18 UTC
