### ISSUE TITLE
Urgency formatting not working

### ISSUE THREAD

**Issue by eigengrau** [DaveDavenport/rofi#162] opened 2015-05-12 12:22 UTC
I’ve noticed that urgency hints don’t seem to be working. I can reproduce this by manually setting urgency on a client using `wmctrl -r firefox -b add,demands_attention`. rofi will not highlight Firefox entry even when `-bg-urgent` is used.

Thanks for making rofi!

**Comment by eigengrau** [comment] 2015-05-12 13:12
Strangely, not all all clients seem to be affected. I’ve read that there are two ways in which clients set their urgency hint. Maybe this makes for the difference between `demands_attention` and clients that seem to work.

**Comment by DaveDavenport** [comment] 2015-05-12 19:15
I noticed this too. 
Currently rofi checks:
 *  _NET_WM_STATE_DEMANDS_ATTENTION
 * XUrgencyHint
and for testing I also added a test for _NET_WM_WITHDRAWN. 

I am not sure why this does not reliable works.

**Comment by DaveDavenport** [comment] 2015-05-12 19:49
Checking further, if I set the dman on the window, and get the window properties (_NET_WM_STATE) I do not get any atoms back.. something goes wrong here.

**Comment by eigengrau** [comment] 2015-05-15 08:46
I don’t know too much about X, sadly. I only came across [this](http://www.reddit.com/r/archlinux/comments/tbj6w/setting_wm_urgent_hint/c4ogc1m), but strangely, when I run `xprop -spy` while adding `demands_attention` via `wmctrl`, nothing shows up in the spy output, even though my WM renders an urgency hint around the window afterward.

**Comment by DaveDavenport** [comment] 2015-05-15 08:48
I noticed the same thing with xprop. What WM are you using?

**Comment by eigengrau** [comment] 2015-05-15 09:11
I’m using bspwm. Is [this](https://github.com/baskerville/bspwm/blob/e9611ded0bcd0ad304025f0685ec28e78d850667/events.c#L385) helpful? I don’t really know any C, but it looks like this is how bspwm detects urgency (not sure if does it correctly, though; but it does show when I set `demands_attention` via `wmctrl`).

**Comment by DaveDavenport** [comment] 2015-05-15 09:14
*Rofi* does do something like that, it checks NET_WM_STATE for  _NET_WM_STATE_DEMANDS_ATTENTION.
(but obviously it cannot listen for the signal setting the DEMANDS.)

**Comment by DaveDavenport** [comment] 2015-07-13 16:09
With  this: https://github.com/hiltjo/seturgent I can confirm the Urgency hint works. The DEMANDS_ATTENTION I cannot figure out,,

**Comment by DaveDavenport** [comment] 2015-12-08 18:18
With latest i3, urgency hint seems to be working well for me. (except that sakura keeps setting urgency hint).

For now I close this one..  Please re-open if there still is an issue.

**Closed by DaveDavenport** 2015-12-08 18:18 UTC
