### ISSUE TITLE
Clean removed binaries

### ISSUE THREAD

**Issue by antoyo** [DaveDavenport/rofi#466] opened 2016-09-17 16:57 UTC
## Version

```
Version: 1.2.0
```

## Configuration

https://gist.github.com/antoyo/cb11d809b24adc96e5cb6e19afc9b779

## Launch Command

```
rofi -show run
```

## Steps to reproduce

* Create a binary
* Launch this binary with rofi
* Delete the binary
* Launch the binary with rofi

## What behaviour you see

* Failed to execute

## What behaviour you expect to see

* The binary should not be listed anymore in rofi

Thanks to fix this issue.

**Comment by DaveDavenport** [comment] 2016-09-17 17:00
Duplicate of #231.
Will see if we can fix this.

**Comment by DaveDavenport** [comment] 2016-09-17 17:49
Realize this might not be so trivial as people also use the history to store commands with arguments.
Checking if it is available might become to expensive then.

Needs more thought :smile:

**Comment by antoyo** [comment] 2016-09-17 19:08
Perhaps we could have a command like `rofi --clean` to run this cleaning process manually?

**Comment by DaveDavenport** [comment] 2016-09-17 19:25
i wonder how big an issue it is. it is only if you uninstall one of your 25 most used applications and have history enabled. You can remove the entry by `shift-delete`.

I will modify it so if execution fails, it is removed from history.

**Comment by antoyo** [comment] 2016-09-17 19:28
Having the application removed from history when execution fails will be fine for me.
Thanks.

**Comment by DaveDavenport** [comment] 2016-09-17 19:29
Added that option to git.

**Comment by DaveDavenport** [comment] 2016-09-17 19:30
Thanks for the report.

**Closed by DaveDavenport** 2016-09-17 19:30 UTC
Labels: Nice To Have
