### ISSUE TITLE
Make elements in horizontal mode have dynamic sizes.

### ISSUE THREAD

**Issue by EdwinPujols** [DaveDavenport/rofi#108] opened 2015-01-14 19:17 UTC
Currently, in horizontal mode the width of the elements is constrained to be equal (so that exactly `max_elements` fit in the row). As a result, unless we pass `-width 100` or a smaller font, most of the elements names will obscured (due the ellipsis).  

It would be nice if, in hmode, the elements had their natural width (like in dmenu). This would imply that the number of visible elements is not constant (in hmode) per page.

**Comment by DaveDavenport** [comment] 2015-01-14 20:47
duplicate of issue #16

**Comment by DaveDavenport** [comment] 2015-01-14 20:50
I worked on this a couple of times. It either resulted in 1.) ugly code. 2.) noticeably slower code.

There are a lot of things to 'keep in mind' and these things makes the code more complex (you want min/max size, as a one entry should not be to big, but also not too small,  paginating is variable, when can or can't you display an extra entry, if you scroll, not one but multiple entries become visiblue, etc. etc.) So I was never happy with my own 'fixes' 

Maybe we can discuss this ? e.g. on IRC? (#gmpc @ irc.freenode.net)

**Comment by DaveDavenport** [comment] 2015-12-08 18:21
Duplicate in #252. Lets continue there for now.

**Closed by DaveDavenport** 2015-12-08 18:21 UTC
Labels: duplicate
