### ISSUE TITLE
rofi-theme-selector steal focus in loop

### ISSUE THREAD

**Issue by dannycolin** [DaveDavenport/rofi#885] opened 2018-12-23 02:04 UTC
**Temporary workaround**
You can duplicate one of the default theme and rename it with a name beginning by the letter `a`.

## Version

1.5.1

## Configuration

https://gist.github.com/dannycolin/fe02588d5bf65bbade2573a3a439ab31

## Launch Command

`rofi -show drun`

## Steps to reproduce

* Open a terminal
* Type `rofi-theme-selector
* Choose a theme that contain an error in it

## What behaviour you see

Rofi show me an error message that if I try to close it, it reopen instantly. 

To get rid of it, I need to open a new TTY with `ctrl + alt + NUM` and depending on how I open rofi-theme-selector I have to:

1. if I open it in a terminal, I need to kill that terminal
2. If I open it with rofi run mode, 
    - I have to open my text editor (vim) and repair the error in the theme
    - Go back to the previous TTY
    - Press Escape

## What behaviour you expect to see

If I press Escape, it should close the error message and go back to the theme list.

**Comment by carnager** [comment] 2018-12-23 08:13
Hmm, I can only reproduce this in one way: Have a theme installed globally and name it in such a way that it appears first in the list. All other cases will make rofi load the first theme of the list after an error.

Still this is kind of nasty and I am not sure if it can even be fixed, have to think about this.

**Comment by ahloiscreamo** [comment] 2019-01-07 15:49
can confirm, i come across same behaviour today.

**Comment by dannycolin** [comment] 2019-01-07 15:53
@ahloiscreamo like @carnager said : make sure the theme isn't the first one in the list. In the meantime as a workaround, I've duplicated the default theme and gave it a name beginning with the letter `a`.

**Comment by ahloiscreamo** [comment] 2019-01-07 16:00
thanks for suggestion,!
im going to do that,

**Comment by ahloiscreamo** [comment] 2019-01-07 16:59
Hi there, i found my own solution which weird but it work.
before this it show the warning if i launch it normally mod+d(exec rofi on i3) 

when this happen i cannot do anything, it wont close and it loop so i had to hard-reset my pc.
so i log in back and launch it via terminal and it behave the same, but this time i can close it by killing it on terminal,
![screenshot from 2019-01-08 00-38-04](https://user-images.githubusercontent.com/9318372/50780405-cc874400-12dd-11e9-8515-f04bcd39fd9e.png)

So because it only show font warning, i went to my config and set the font like -

![screenshot from 2019-01-08 00-45-20](https://user-images.githubusercontent.com/9318372/50780828-e5dcc000-12de-11e9-9072-4e01a4cb9df5.png)

i went to set the same font on i3 config
![screenshot from 2019-01-08 00-48-54](https://user-images.githubusercontent.com/9318372/50780966-3e13c200-12df-11e9-8076-246f9b60bed2.png)

after that it work fine, i notice it highlight some theme ,i dont know what that mean.
![screenshot from 2019-01-08 00-52-50](https://user-images.githubusercontent.com/9318372/50781239-d5791500-12df-11e9-85b8-75b849e0c2d9.png)

so to clarify, before this it launch just fine, it only give warning when i try to change theme, now it work after setting the font on both i3config and rofi config.so that is my workaround..

**Comment by DaveDavenport** [comment] 2019-02-02 12:14
No reply checking commit, assuming it is fixed.

**Closed by DaveDavenport** 2019-02-02 12:14 UTC
