### ISSUE TITLE
Behavior of `-eh` changed from 1.1.0 to 1.2.0

### ISSUE THREAD

**Issue by alaviss** [DaveDavenport/rofi#502] opened 2016-11-19 02:13 UTC
## Version

Output of `rofi -v`
Version: 1.2.0

## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))
https://gist.github.com/alaviss/cac68ad7b9b83428e083e7c1b3dc4860

## Launch Command

The commandline used to launch **rofi**
```
$ echo 'test' | rofi -dmenu -eh 2
```

## Steps to reproduce

* Step 1 Run the above command

## What behaviour you see

* The word 'test' is vertically top-aligned

## What behaviour you expect to see

* The word 'test' is vertically centered

**Comment by DaveDavenport** [comment] 2016-11-19 04:58
Related to #449

**Comment by alaviss** [comment] 2016-11-20 17:01
Is there any way to create the same vertical padding as 1.1.0?

**Comment by DaveDavenport** [comment] 2016-11-20 19:58
`-eh` its purpose is for multi-line entries.  there you want each entry to start at a fixed interval, instead of depending on number of lines.. 
If you use it for just padding, read the suggestion in #449.

What are you using it for?

**Comment by alaviss** [comment] 2016-11-21 00:50
I use it solely for padding. Is there any way to highlight the margin from `-line-margin`? It is necessary for my `rofi` theme

**Comment by DaveDavenport** [comment] 2016-11-21 06:24
Duplicate of #449 

In #449 this was added:
```
	-line-padding [number]                  Padding within rows
```

**Closed by DaveDavenport** 2016-11-21 06:24 UTC
