### ISSUE TITLE
[Feature request] ] Single click to accept - Using rofi for personal context menus

### ISSUE THREAD

**Issue by snippins** [DaveDavenport/rofi#598] opened 2017-05-27 10:25 UTC
# Use case 
For many mouse-heavy apps, like Gimp, Inkscape, I notice my right hand have to switch between mouse & keyboard all the time which is quite annoying. Thus I setup rofi to open at the mouse location (ex: Super + right click) as a personal context menus to send frequent commands/key strokes without leave the mouse. Its work fine but having to double click to choose an entry is quite annoying and inconsistent to how context menus work. 

# Suggestion
Add an option to use single click to accept an entry. This is related to another report [here](https://github.com/DaveDavenport/rofi/issues/441) but with different use-case.

**Comment by sardemff7** [comment] 2017-05-27 22:52
Duplicate of #441.

**Closed by sardemff7** 2017-05-27 22:52 UTC
Labels: enhancement, Nice To Have
