### ISSUE TITLE
passive aggressive behaviour

### ISSUE THREAD

**Issue by fx3O2** [DaveDavenport/rofi#341] opened 2016-02-14 09:11 UTC
Warning: This developer seems to be kinda passive agressive against serious questions and problems I have with this software. Please look down to me how noob I am just asking for help. On issue #340 I didn't even know I can pass other arguments to dmenu as well. I thought the `fuzzy` option is related to rofi itself, not to the dmenu project. Also, there is no need for a description in #339 if all the question is in the title. Please note, there are other questions as well, where you didn't care about your serious issue tracker:

- #325 
- #171

Not everyone is into this project like you, most of us don't even know how to write C nor do they want to. No, I don't understand dmenu. I'm just a stupid user trying to learn how things work. Please kill me for beeing human.

**Comment by DaveDavenport** [comment] 2016-02-14 10:10
I normally try to answer question posted, but they are closed ( #325 ) (they are not issues) and marked as question. Questions that might actually be caused by a bug are left open ( #171 ) until resolved or the cause is clear, then closed.

I however expect users to:

- Read the manpage
- Investigate: I am not going to answer general questions like 'what is dmenu'.
- Put effort into your Report. You expect effort from me to answer it, be kind enough to do the same.

See also [website](https://davedavenport.github.io/rofi/p09-Contact.html).

If this is not acceptable, feel free not to  use **rofi**.

I develop **rofi** in my free time, I do not get payed for it. I put it online because other people might find it useful. Posts like these are depressing and will only result in developers no longer making the tools they build for them self available online.

**Closed by DaveDavenport** 2016-02-14 10:10 UTC

**Comment by cjbarroso** [comment] 2018-12-31 22:55
We have this kind of people from the dawn of the free software movement. I've learnt to ignore them, but you took the time to try to educate him, kudos for you. Thank you for a fine piece of software. Sorry for commenting on a closed issue, I'm kinda drunk on the new year's eve

**Comment by DaveDavenport** [comment] 2019-01-01 22:05
Happy new year!
