### ISSUE TITLE
"Path" in .desktop files are not respected

### ISSUE THREAD

**Issue by joemaro** [DaveDavenport/rofi#487] opened 2016-10-23 17:07 UTC
## Version

1.2.0
(x64 from arch repo)

## Configuration

Output of `rofi -dump-xresources` is here:
http://hastebin.com/oqanakeker.sql
(gist thing wouldn't work for me sorry)

## Launch Command

rofi -show combi

## Steps to reproduce

* select an entry that comes from a .desktop file in .local/share/applications and that needs the path variable to be functioning.
* see how the entry won't run

## What behaviour you see

* Programs that need the path variable in .desktop files to be passed on to, won't run when launched with rofi 1.2.0 but do with dmenu and kupfer.
2 examples for me are xonotic & sauerbraten, both of which are in the homefolder (in contrast to being in /usr/bin etc...) , so the executable needs to be run from with the path where the data/content is, to be working.

## What behaviour you expect to see

* that they run :)

(hey thanks soooo much for this amazing software. It's such a beauty!!!! <3 )

**Comment by DaveDavenport** [comment] 2016-10-23 18:20
Duplicate of #482 .

**Closed** 2016-10-23 18:19 UTC
