### ISSUE TITLE
Got error: -1 Socket operation on non-socket

### ISSUE THREAD

**Issue by notaduck** [DaveDavenport/rofi#763] opened 2018-02-03 21:56 UTC
## Version

`Version: 1.5.0-dirty (tags/1.5.0)`

## Configuration

https://gist.github.com/notaduck/020fdfd952d867031e674977ecfc0256

## Launch Command

`rofi -modi run,drun,window -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font "Noto Sans 8"`

## Steps to reproduce

run the rofi launc cmd.

## What behaviour you see

```
xkbcommon: ERROR: couldn't find a Compose file for locale "en_DK.utf8"

(process:1758): Helper-WARNING **: Failed to set lock on pidfile: Rofi already running?

(process:1758): Helper-WARNING **: Got error: -1 Socket operation on non-socket

```

## What behaviour you expect to see

I expected that the rofi menu would show up ;)

**Comment by notaduck** [comment] 2018-02-03 22:02
I just tried to manually run the cmd instead of using the hotkey for launching the rofi menu through i3wm's config and it locks the hole system and it doesn't seems like I'm able to close it again..... I have to turn off the whole computer

**Comment by DaveDavenport** [comment] 2018-02-03 22:04
Can you pastebin the complete rofi -h output.

@sardemff7 could the missing compose file cause the lock-up?

**Comment by notaduck** [comment] 2018-02-03 22:06
Ofcourse https://gist.github.com/notaduck/539221e694e1ce7217fe8b4874a9cc8a

**Comment by notaduck** [comment] 2018-02-03 22:07
I am able to open rofi with `rofi -show run` but if I use `drun` then it doesn't work and I have to kill the process by hand.

**Comment by DaveDavenport** [comment] 2018-02-03 22:08
So it does not lock up? does it still give the xkcommon error?

**Comment by DaveDavenport** [comment] 2018-02-03 22:10
Can you run rofi with full debug output?
```
G_MESSAGES_DEBUG=all rofi -show drun
```
and pastebin the output it gives until locking up?

**Comment by notaduck** [comment] 2018-02-03 22:10
If I run it manually in the terminal then yes, the systems is getting locked/freezes.
But if I use the hotkey then it is just laying there as an active process where I have to kill it before I can use `run` which works flawless.

**Comment by DaveDavenport** [comment] 2018-02-03 22:11
Weird, first time I heard of this behavior.

**Comment by notaduck** [comment] 2018-02-03 22:15
![img_20180203_231247](https://user-images.githubusercontent.com/9454064/35772064-0aa2579e-0938-11e8-92ff-f240139907c4.jpg)

Sry for the bad quality but it literaly locks up and I've to restart the laptpo everytime I run `rofi -show drun`

**Comment by notaduck** [comment] 2018-02-03 22:17
I don't know if this helps:
```
[daniel@laptop ~]$ ls -al .ssh
total 20
drwx------  2 daniel daniel 4096 Dec 26 16:27 .
drwx------ 73 daniel daniel 4096 Feb  3 23:16 ..
-rw-------  1 daniel daniel 1679 Nov 23 23:27 id_rsa
-rw-r--r--  1 daniel daniel  395 Nov 23 23:27 id_rsa.pub
-rw-r--r--  1 daniel daniel 3530 Jan 14 19:15 known_hosts
```
It looks like it is looking for a file which isn't there

**Comment by DaveDavenport** [comment] 2018-02-03 22:55
instead of restarting laptop, there are 2 solutions:

Ctrl-Alt-F2 -> go to terminal and kill rofi
before s tarting rofi do 'sleep 20 ; killall rofi` on another terminal.

It looks like there is extra output on the top, broken theme?  can you grab this?

**Comment by notaduck** [comment] 2018-02-03 23:33
Luckly I was able to do it, [here](https://gist.github.com/notaduck/329504fbbe2f61b4bea95a97f76809e2) it is.

**Comment by sardemff7** [comment] 2018-02-04 08:27
Compose is optional, rofi should still work without it, with no Compose support.
To fix that part, just use `en_DK.UTF-8` as your locale or add an alias to `/usr/share/X11/locale/locale.alias` (please submit it to libX11 upstream if you do).

I would run `G_MESSAGES_DEBUG=all strace rofi… &>rofi-trace.log`, it should tell us where it locks quite precisely, and then maybe we can figure out how to fix it.

**Comment by notaduck** [comment] 2018-02-04 09:51
I got lucky and pulled a few [lines](https://gist.github.com/notaduck/bbc534872609423ecb569958c8aa1db6)

**Comment by sardemff7** [comment] 2018-02-04 10:49
I meant the full rofi command in strace, like G_MESSAGES_DEBUG=all strace rofi -show drun &>rofi-trace.log`, the one that hang.

**Comment by notaduck** [comment] 2018-02-04 11:06
https://gist.github.com/notaduck/f90e5e28fb1cc3f2054c1bfbd6a0f466
There is 760383 lines in total but I've no idea where I should upload that as a poaste, I assume you don't want to download a .txt file from some random dude.

**Comment by sardemff7** [comment] 2018-02-04 11:52
Hopefully, the last thousands should have the info we want. It probably hangs on a file opening or reading, since it’s only with drun, it’s probably some malformed file we should handle better.

**Comment by notaduck** [comment] 2018-02-04 12:56
The last thousands is all the same like where it is complaining about numix just like the one I sendt

**Comment by DaveDavenport** [comment] 2018-02-04 12:57
Can you try with stock-config, just to check:

```rofi -show drun -no-config ```

**Comment by notaduck** [comment] 2018-02-04 13:49
Same rresoult
```
[daniel@laptop ~]$ rofi -show drun -no-config
xkbcommon: ERROR: couldn't find a Compose file for locale "en_DK.utf8"
Mode drun is not enabled. I have enabled it for now.
Please consider adding drun to the list of enabled modi: modi: window,run,ssh,drun.
Terminated
```

The system hangs

**Comment by sardemff7** [comment] 2018-02-04 14:06
It may not be useful, but when someone asks for a log, you give them the full log (or the part they ask for), otherwise they may miss relevant information. You can upload files on the bug report directly.
If the strace cannot help, we’d need a gdb trace. You can run `sleep 5; rofi -show drun`, then quickly switch to another VT, run `gdb rofi $(pgrep rofi)`, then `bt full`.

**Comment by notaduck** [comment] 2018-02-04 14:11
The case is there is no way I could do that sinse the whole system is locked up after I use drun.

**Comment by sardemff7** [comment] 2018-02-04 16:05
So you tried VT-switch *before* rofi starts? The system may look frozen, but it could be just rofi grabbing the keyboard and mouse. Do you have a LED on that machine for the HDD activity? If so, does it light up (almost) without blinking when the system is locked? Can you try to SSH to that machine?

**Comment by sardemff7** [comment] 2018-02-04 16:07
And please upload the full strace log on this bug report.

**Comment by notaduck** [comment] 2018-02-04 16:12
Here is the full [log file](https://owncloud.techknight.eu/index.php/s/BD17zz8dsBHZu5Z) I havent tried VT so far, and there isn't any led indicators on the machine. I'm going to try to SSH into the machine later today (But I think I will be able to do so, since I still can move my mouse around but I can't do anything besides that)

**Comment by notaduck** [comment] 2018-02-04 16:26
I haven't tried with VT-switch(I've no clue about how it workd), but after I've been playing arround for some while i seems like I'm able to get to `tty` and my mouse isn't completly frozen, I'm just not able to press/click on anything. And yes, Iøm able to ssh into the machine and kille the process and then it is fully functional again.

Here is the full [log file](https://owncloud.techknight.eu/index.php/s/BD17zz8dsBHZu5Z)

**Comment by sardemff7** [comment] 2018-02-04 17:06
VT-switch is `Ctrl-Alt-Fx`, VT is another name for TTY (well, the TTY is *in* the VT). Once there, you can safely gdb the running rofi and get a backtrace.

**Comment by sardemff7** [comment] 2018-02-04 17:10
From the strace log, I can see the code is busy looping at the cache icon theme step, I’ll look into it. Could you upload/gist the `/usr/share/icons/Numix/index.theme` file?

**Comment by notaduck** [comment] 2018-02-04 18:25
Aaaa! Thanks for the precise explanation!
And  [/index.theme](https://gist.github.com/notaduck/0b253c520329b8d7a8ae023fa50efa15) should be here.

**Comment by sardemff7** [comment] 2018-02-04 18:43
Ok, the issue is obvious now: the theme inherits itself. I’m not sure it’s valid, but I’ll try to handle that properly.
I’ll check how other projects handle that, and maybe you should fill a bug report to Numix upstream to drop that line.

**Comment by notaduck** [comment] 2018-02-04 19:10
Thanks for the quick responses throughout the day! I will try to remove numix as a start to see if that helps, and then let them know

**Comment by sardemff7** [comment] 2018-02-04 19:12
Should be fixed now, with a test for that. :-)

**Closed** 2018-02-04 19:11 UTC

**Comment by notaduck** [comment] 2018-02-04 19:31
It seems like it works fine for now ;) Thanks!
