### ISSUE TITLE
Window switcher is much too big

### ISSUE THREAD

**Issue by s3rb31** [DaveDavenport/rofi#495] opened 2016-11-06 23:53 UTC
## Version

`Version: 1.2.0-165-gda2e6a2-dirty (makepkg)`

## Configuration

https://gist.github.com/s3rb31/bee3285d569b86c640c7615d010373e4

## Launch Command

`rofi -show window`

## Steps to reproduce

* Execute the command

## What behaviour you see

* The window is much bigger than it should be

![rofi-2016-11-07-0100](https://cloud.githubusercontent.com/assets/6666298/20043022/9b69564c-a485-11e6-8841-8b6515794cff.png)

It seems like the window-switcher now enforces the `rofi.lines` configuration directive. IMHO it was much nicer when it did not.

Edit: Also the colon in the prompt is missing. Here is another picture from the stable version 1.2.0:

![rofi-2016-11-07-0101](https://cloud.githubusercontent.com/assets/6666298/20043031/c742361c-a485-11e6-8610-586ffec289f0.png)

## What behaviour you expect to see

* A nice and fit window ;)

**Comment by DaveDavenport** [comment] 2016-11-07 07:28
duplicate of #488

**Closed by DaveDavenport** 2016-11-07 07:28 UTC

**Comment by s3rb31** [comment] 2016-11-07 11:18
Oops. Thanks.

**Comment by DaveDavenport** [comment] 2016-11-07 16:15
no problem.
