### ISSUE TITLE
Bug in urgent row coloring

### ISSUE THREAD

**Issue by mardukbp** [DaveDavenport/rofi#173] opened 2015-05-27 22:05 UTC
I configured the background and foreground colors for urgent rows and I am calling rofi with a certain set of such rows. Some of these rows have the specified fg and bg colors, others do not show the text until they are highlighted. There doesn't seem to be a pattern. It seems like a bug.

**Comment by DaveDavenport** [comment] 2015-05-28 06:21
Without more information there is no way for me to check/reproduce this.
Please provide more information.  (e.g. how you call rofi, the output of -dump-xresources).

**Comment by mardukbp** [comment] 2015-05-30 20:05
I was calling rofi with `-bg-urgent #ff0000 -fg-urgent #ffffff`. Then I read the man page and learned that I should rather use `-color-urgent "#ff0000,#ffffff,#eee8d5,#dc322f,#fdf6e3"`. Now I am passing this option to rofi, but it ignores my settings for the first two colors resorting to the default `#fdf6e3,  #dc322f`. I have not modified my `~/.Xresources` file.

**Comment by DaveDavenport** [comment] 2015-05-30 20:08
You either use the old `-bg-urgent` or the new color style, for this you need to enable 'new style ' first by setting `rofi.color-enabled:                  true`

**Comment by mardukbp** [comment] 2015-05-30 20:21
Using `-color-enabled` now `-color-urgent` works as expected. Now the rows that were previously blank are colored using bgalt. I am calling rofi with: `cat pylab | $rofi -u 0,114,117,142,146,159,171,175 -eh 2 -sep '|' -color-enabled -color-urgent "#0000ff,#000000,#ff0000,#dc322f,#fdf6e3" -dmenu -p 'pylab '`

Here is `rofi -dump-Xresources`

```
rofi.modi:                 window,run,ssh
rofi.opacity:              100
rofi.width:                50
rofi.lines:                15
rofi.columns:              1
rofi.font:                 mono 12
rofi.fg:                   #002B36
rofi.bg:                   #FDF6E3
rofi.color-enabled:        false
rofi.color-normal:         #fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5
rofi.color-urgent:         #fdf6e3,#dc322f,#eee8d5,#dc322f,#fdf6e3
rofi.color-active:         #fdf6e3,#268bd2,#eee8d5,#268bd2,#fdf6e3
rofi.color-window:         #fdf6e3,#002b36
rofi.fg-active:            #268BD2
rofi.fg-urgent:            #DC322F
rofi.hlfg-active:          #FDF6E3
rofi.hlfg-urgent:          #FDF6E3
rofi.bg-active:            #FDF6E3
rofi.bg-urgent:            #FDF6E3
rofi.hlbg-active:          #268BD2
rofi.hlbg-urgent:          #DC322F
rofi.bgalt:                #FDF6E3
rofi.hlfg:                 #EEE8D5
rofi.hlbg:                 #586E75
rofi.bc:                   #002B36
rofi.bw:                   1
rofi.location:             0
rofi.padding:              5
rofi.yoffset:              0
rofi.xoffset:              0
rofi.fixed-num-lines:      false
rofi.terminal:             x-terminal-emulator
rofi.ssh-client:           ssh
rofi.ssh-command:          {terminal} -e {ssh-client} {host}
rofi.run-command:          {cmd}
rofi.run-list-command:     
rofi.run-shell-command:    {terminal} -e {cmd}
rofi.disable-history:      false
rofi.levenshtein-sort:     true
rofi.case-sensitive:       false
rofi.sidebar-mode:         false
rofi.lazy-filter-limit:    5000
rofi.eh:                   1
rofi.auto-select:          false
rofi.parse-hosts:          false
rofi.combi-modi:           window,run
rofi.pid:                  /run/user/1000/rofi.pid
rofi.key-window:           
rofi.key-run:              
rofi.key-ssh:
```

**Comment by DaveDavenport** [comment] 2015-05-30 20:26
```
rofi.hlfg-active:          #FDF6E3
rofi.hlfg-urgent:          #FDF6E3
rofi.bg-active:            #FDF6E3
rofi.bg-urgent:            #FDF6E3
```

This is the problem. It looks like the defaults are wrong.
Thx.

**Comment by mardukbp** [comment] 2015-05-30 21:05
Now I understand. Urgent rows are sorted alphabetically and are colored alternating between bg-urgent and bgalt-urgent. Problem solved! Thanks a lot.

**Comment by DaveDavenport** [comment] 2015-05-30 21:42
Defaults should be fixed.

**Comment by DaveDavenport** [comment] 2015-05-31 07:29
Seems defaults where ok.. We have way to many options :disappointed:

**Closed by DaveDavenport** 2015-05-31 07:29 UTC
Labels: bug
