### ISSUE TITLE
Rofi not recognized by AwesomeWM as a client

### ISSUE THREAD

**Issue by vlaze** [DaveDavenport/rofi#551] opened 2017-01-30 15:07 UTC
## Version

Output of `rofi -v`

Version: 1.3.1-208-g6a01c9c-dirty (master)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

https://gist.github.com/vlaze/bf7a9b9e9fd4c9eaa612ad5725de5732

## Launch Command

The commandline used to launch **rofi**

`rofi -show run`

## Steps to reproduce

* Step 1: Edit your AwesomeWM rc.lua file in order to do something when a client exits. Impose this client to be Rofi:

```
 --Place this snippet at the end of the file, outside of other sections:

 client.connect_signal("unmanage", function(c)
       print(c.class) -- Debug purposes
       if c.class == "Rofi" then
            --Insert any condition, i.e. awful.util.spawn(terminal) or awesome.restart
       end
 end)
```
 

* Step 2: Launch AwesomeWM from Xephyr using:
`Xephyr -ac -nolisten tcp -br -noreset -screen 800x600 :2`
`DISPLAY=:2.0 awesome -c /path/to/rc.lua`
...if you want to use the debugging option. Else, just start AwesomeWM the way you prefer.

* Step 3: Launch Rofi from a terminal inside AwesomeWM.

## What behaviour you see

* - AwesomeWM can enter the 'if' condition if we use any other class name (i.e. setting Nautilus as a class name and closing a Nautilus client), but will never work with Rofi. 

## What behaviour you expect to see

* - Rofi should be tweaked in order to be detected by its class name not only by a window manager, but by any other program that could require that information in order to make Rofi more programmer-friendly. This could lead to lots of customized Rofi setups working along with other applications which would increase the usability of the program.

**Comment by DaveDavenport** [comment] 2017-01-30 15:09
Duplicate of? https://github.com/DaveDavenport/rofi/issues/549

**Comment by vlaze** [comment] 2017-01-30 15:10
I am using the updated version that fixes #549. Now Rofi has class, but that class cannot be used to identify it as a client just like any other application.

**Comment by DaveDavenport** [comment] 2017-01-30 15:14
The problem is not clear to me then.

**Comment by vlaze** [comment] 2017-01-30 15:21
When I make AwesomeWM to 'react' to a window being closed, I use a specific function (`unmanage`). Then, for specifying _which_ window has to be closed in order to activate my code sequence, I use the `if` statement and the window class of the application so that the WM can identify without doubt the window its behaviour needs to be aware of. 

This works for every single application in the system, and the WM will not fail at entering the condition; but it has difficulties with Rofi.

**Comment by DaveDavenport** [comment] 2017-01-30 15:23
Does it work if you run rofi with `-normal-window`?

**Comment by vlaze** [comment] 2017-01-30 17:40
Just had the time to test. Works perfectly. Thank you!

**Comment by DaveDavenport** [comment] 2017-01-30 17:40
That

**Comment by DaveDavenport** [comment] 2017-01-30 17:43
rofi uses override redirect, to place the window on top and outside of meddling WM's. 
See: https://tronche.com/gui/x/xlib/window/attributes/override-redirect.html
So maybe your lua script can be adjusted to take this into account.

I don't recommend running f.e. the window switcher in `-normal-window` mode as it allows you to move away from rofi close/open windows (and rofi does not keep track of this).

**Comment by vlaze** [comment] 2017-02-01 15:58
I have just been able to check that, using -normal-window, I get this layout when I hide the top bar of my WM; which does not happen using any other application. Check [https://www.reddit.com/r/awesomewm/comments/5qtmyi/i_need_help_debugging_this/](url)

**Comment by DaveDavenport** [comment] 2017-02-01 16:38
In normal window mode rofi takes the size it gets assigned to it, it does not force a size itself, this might be causing problems.

Can you (from lua) tell rofi window to be a certain size?

**Comment by DaveDavenport** [comment] 2017-02-01 16:46
Or try this patch:
```patch
diff --git a/source/view.c b/source/view.c
index 097ea19..f3c1108 100644
--- a/source/view.c
+++ b/source/view.c
@@ -1086,7 +1086,7 @@ static void rofi_view_refilter ( RofiViewState *state )
     }
 
     // Make sure we enable fixed num lines when in normal window mode.
-    if ( ( CacheState.flags & MENU_NORMAL_WINDOW ) == 0 ) {
+    {
         int height = rofi_view_calculate_height ( state );
         if ( height != state->height ) {
             state->height = height;
```

**Comment by vlaze** [comment] 2017-02-01 18:16
> Can you (from lua) tell rofi window to be a certain size?

Unfortunately, I don't know how to do this at this time, as I have started with Lua not a long time ago. 


> Or try this patch:

This worked! Now Rofi looks the same size as if it was run via `rofi -show run`, but behaves as a regular AwesomeWM client (draggable, resizable...). Solved the problem for me, but I'll leave the closing task to you if you don't mind. If you need any more information about this issue, feel free to contact me here. Thanks for your time!

**Closed** 2017-02-01 20:05 UTC
Labels: Need more information
