### ISSUE TITLE
-bg-active only works if the active window is first

### ISSUE THREAD

**Issue by taylor-peterson** [DaveDavenport/rofi#294] opened 2015-12-06 02:38 UTC
Repro Steps:
1. Open two windows
2. Select the second
3. Start rofi in window mode
4. Observe correct bg-active coloring
5. Select the first window
6. Start rofi in window mode
7. bg-active coloring is not present - bg coloring is used (but fg-active coloring is correct)

Note: I'm using rofi 0.15.7 on ubuntu 14.04 with i3 4.11.

**Comment by DaveDavenport** [comment] 2015-12-06 10:10
Cannot reproduce this in *git*.
Could you try to reproduce this on an up2date version?

**Comment by DaveDavenport** [comment] 2015-12-08 18:14
Can you report what window manager?

**Comment by taylor-peterson** [comment] 2015-12-15 04:16
i3 version 4.11

I'll try out the git version when I get a chance.

**Comment by DaveDavenport** [comment] 2016-02-18 07:10
closing..  If problem exists in newer version please re-open.

**Comment by taylor-peterson** [comment] 2016-03-05 16:26
I tried this out again and it seems to be working correctly unless the active window is GNOME Terminal. In that case, the repro steps still apply.

I'm now on rofi version 1.0.0-devel. All other versions remain the same.

**Comment by taylor-peterson** [comment] 2016-03-05 16:28
Note that it looks like I can't reopen this issue myself.

**Comment by DaveDavenport** [comment] 2016-03-05 16:30
pastebin config,

**Comment by taylor-peterson** [comment] 2016-03-05 16:34
The relevant bit of my i3 config is here: http://pastebin.com/mTraHcaH

Let me know if you need more.

**Comment by DaveDavenport** [comment] 2016-03-05 16:41
You are using the deprecated theme setup, here you cannot set all the right color fields. (bgaltactive)

```
! Use extended color scheme
rofi.color-enabled:                  true
! Color scheme for normal row
rofi.color-normal:                   argb:0000000, #dbdfbc, argb:3affffff, #dbdfbc, #02143f
! Color scheme for urgent row
rofi.color-urgent:                   argb:0000000, #ff817f, argb:3affffff, #ff817f, #02143f
! Color scheme for active row
rofi.color-active:                   argb:0000000, #6aa4ff, argb:3affffff, #6aa4ff, #02143f
! Color scheme window
rofi.color-window:                   argb:ee27201a, #dbdfbc, #dbdfbc
```

**Comment by DaveDavenport** [comment] 2016-03-05 16:48
Something like this?
```
! ------------------------------------------------------------------------------
! ROFI Color theme
! ------------------------------------------------------------------------------
rofi.color-enabled: true
rofi.color-window: #222222, #333333, #000000
rofi.color-normal: #222222, #888888, #222222, #285577, #ffffff
rofi.color-active: #1b3a51, #ffffff, #1b3a51, #285577, #ffffff
rofi.color-urgent: #900000, #ffffff, #900000, #285577, #ffffff
```

**Closed** 2016-03-05 17:05 UTC
Labels: Need more information, Needs Testing

**Comment by taylor-peterson** [comment] 2016-03-05 17:09
Using those in the rofi config file did the trick. Thank you very much!

**Comment by taylor-peterson** [comment] 2016-03-05 17:10
I am curious though - why did adding in bgaltactive fix the issue? I wouldn't have expected different behavior for terminals.

**Comment by DaveDavenport** [comment] 2016-03-05 17:11
terminal had little todo with it, it was the even/uneven position in the list. (alternate row color)

Moving to rofi 1.0 I will remove the old coloring stuff, it is the right time.

**Comment by taylor-peterson** [comment] 2016-03-05 17:13
Ah. That makes sense then. Thanks again!

**Comment by DaveDavenport** [comment] 2016-03-05 17:14
no problem.
